### ISSUE TITLE
admin page link & admin page

### ISSUE THREAD

**Issue by aeggum** [mswysocki/Madison-Student-Apartment-Finder#11]
One thing I added quickly after users was 'admin' users.  If you sign in and you are an admin, you'll be redirected to the admin page.  The page was just quickly thrown together and has a list of all users and a table of listings.  

Users are defaulted to non-admin, but it can be toggled in the console.  
Just want to throw this out there for you all to see.   

Right now there is one admin user.  To see the differences and the admin page, the log-in on msaf.heroku.com is a@a.com and the password is just password. 

Check it out!

Anyways, there are some issues:
1) The admin page link is still on the left side of the banner
2) Searching doesn't work on the admin page (caused by case-sensitivity, will be fixing tonight)
3) Table is not sortable on the admin page (same cause as 2)

**Comment by cromdenne** [comment]
I fixed the link on the banner.  A couple other small things I've noticed that we might need to address:
- When you flag a listing, you shouldn't be allowed to flag it again.  We'll have to look at changing the option to flag that listing more than once.
- Maybe this is just me being nitpicky, but the the submit buttons for the create and update listing pages say "Create List" and "Update List" and it could be "Create Listing" and "Update Listing" instead.
- Is there a way to edit the output of certain fields on the view listing page?  Mainly, I think we should change the true/false outputs to be yes/no, and the Type of Residence output should be either house or apartment.

**Comment by aeggum** [comment]
I agree with all of those points.  

For the third one, I don't know exactly how to do it now but I'm sure it's fixable; I've been thinking about that for awhile.  I'll look into that when I get the chance.

Edit: I've fixed the issue of the second bullet point as far as I can tell.

**Comment by xibaca** [comment]
Hey, it looks nice. Actually you guys did a great job so far! I really like
it.
I will get back to work tomorrow morning, starting from improving the Admin
page (CSS speaking).

2012/4/9 Adam Eggum <
reply@reply.github.com

> One thing I added quickly after users was 'admin' users.  If you sign in
> and you are an admin, you'll be redirected to the admin page.  The page was
> just quickly thrown together and has a list of all users and a table of
> listings.
> 
> Users are defaulted to non-admin, but it can be toggled in the console.
> Just want to throw this out there for you all to see.
> 
> Right now there is one admin user.  To see the differences and the admin
> page, the log-in on msaf.heroku.com is a@a.com and the password is just
> password.
> 
> Check it out!
> 
> Anyways, there are some issues:
> 1) The admin page link is still on the left side of the banner
> 2) Searching doesn't work on the admin page (caused by case-sensitivity,
> will be fixing tonight)
> 3) Table is not sortable on the admin page (same cause as 2)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mswysocki/Madison-Student-Apartment-Finder/issues/11

## 

Guilherme Santos G. Baptista
Graduando em Cincia da Computao pela UFCG
LSD - Laboratrio de Sistemas Distribudos

**Comment by aeggum** [comment]
So I've fixed the other issues brought up in the original post.  I did take out searching for users, for now.  I can add this back in when I change the schema for users; not too hard, just a pain.  Anyways, for now, all else is working.

The other two bullet points will be a little bit more interesting, hopefully I or someone can get something on those soon.

**Comment by xibaca** [comment]
Sounds fine. I think that we can use some Javascript to make the flag button disabled after clicked but then if the page is loaded again, we have to have a way of knowing that listing was already flagged and then disable it automatically, otherwise the disabling would work just once.

**Comment by xibaca** [comment]
In the Search Results page, the table could also contain this ~previous~ and ~next~ thing that displays up to an amount of results per time.
What do you guys think?

And, should I CSS this page tables to look like the other one from the page mentioned above? I could do it easily as everything is already done there. Or even, I can try making that implementation generic to apply automatically to these tables maybe by creating a "table" class.

**Comment by xibaca** [comment]
Also, what else do you guys think I should do to improve this iterations features, from the user`s perspective. I am with lots of free time up to thursday this week, mainly on Thurday morning. I want to spend that time doing something useful for the project.

**Comment by cromdenne** [comment]
Guilherme, I think the table on the search results page might be nice on the administrator page, if you can apply that CSS there.  It has all of the information on each residence, which would probably be useful for the administrator.  However, I think that table should be edited a little bit on the search results page.  Right now it's just a little cluttered, and if we end up adding images and ratings it'll be more difficult to display.  Maybe look at the sample UI we had in the Requirements doc.  Something more spread out like that would probably be friendlier from a user perspective.  But I definitely think the next/previous option is a good idea in both cases.

**Comment by aeggum** [comment]
For the main page's search results, I've always thought that they could have a lot less fields displayed.  As shown here.  https://docs.google.com/drawings/d/13d-A1Ea9LnfPrn0XQD2h1q2jPA0hkF_86pBnFQeBk_c/edit  

Now obviously, we don't have images yet, nor do we have reviews or ratings, but **maybe we could display the address larger (if possible), zip code, then bedrooms, bathrooms, and rent for sure.  Then if people want to see more info about it they can click 'Show' to see all info.**  I don't think we need to show every field on the results page.

**If you want to make the table a link, like the admin page table, that would be something to do too.**

I would imagine that changing the way the table looks will be _quite_ a bit of work, but if we want it to look something like the picture it will have to be done.   

As for 'pagination', yeah, I will look into adding that back to the search results page.  When I first implemented search, I also had sorting and paging and something broke search so I took them both out.  I will look to add it back but probably not before thursday.  I'll set it up to have something around 5 results per page or so.

I've bolded what I think could be something to work on.

**Comment by aeggum** [comment]
Looks like we are thinking along the same lines, Cory! 

Anyways, later tonight when I am at home, I will make both of you admin users (if you aren't already) so you can get to the admin page regularly.

Edit: I made a new meta-ticket with all of the issues brought up in here, just to de-clutter.

**Comment by xibaca** [comment]
You guys are absolutely right! When I did that CSS for the Search Results,
I had completely forgotten about that sample image which I should have
looked into to use as a guide, so I just did whatever came out of my mind.
Yeah, it will be way if it looks that way.

"Now obviously, we don't have images yet, nor do we have reviews or

> ratings, but **maybe we could display the address larger (if possible),
> then bedrooms, bathrooms, and rent for sure.  Then if people want to see
> more info about it they can click 'Show' to see all info.**  I don't think
> we need to show every field on the results page."

I think I know how to do that!

**If you want to make the table a link, like the admin page table, that

> would be something to do too.**

Sorry I did not understand exaclty what you meant here.

---

Now that you guys refreshed my mind about that sample, I definitely think
the results displayed should look like that!

2012/4/10 Adam Eggum <
reply@reply.github.com

> Looks like we are thinking along the same lines, Cory!
> 
> Anyways, later tonight when I am at home, I will make both of you admin
> users (if you aren't already) so you can get to the admin page regularly.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/mswysocki/Madison-Student-Apartment-Finder/issues/11#issuecomment-5058956

## 

Guilherme Santos G. Baptista
Graduando em Cincia da Computao pela UFCG
LSD - Laboratrio de Sistemas Distribudos

**Comment by aeggum** [comment]
I mean, make the table entry itself a clickable link.. So clicking anywhere on the table entry will take you to the listing page relating to that entry.  It's how the table on the admin page works, though the mouse doesn't change when you hover.

I'm not sure if this is what we will want to do but it's an idea..

**Comment by xibaca** [comment]
I see. I think that is better that way, requires less clicks from the user;
I will make the entries links then!
