### ISSUE TITLE
Idea: Replace [About Us] with link to [Admin Page] for signed in admins

### ISSUE THREAD

**Issue by aeggum** [mswysocki/Madison-Student-Apartment-Finder#15]
The thought just crossed my mind.  Sound like a decent idea?

I don't think it would be too hard, just some styling changes, perhaps, and then a few if statements moved around in the banner's code.

**Comment by xibaca** [comment]
Yeah, sounds reasonable!
I think that should be easy to do and is a good idea.
So far I've having problems accessing the Admin Page.

2012/4/14 Adam Eggum <
reply@reply.github.com

> The thought just crossed my mind.  Sound like a decent idea?
> 
> I don't think it would be too hard, just some styling changes, perhaps,
> and then a few if statements moved around in the banner's code.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mswysocki/Madison-Student-Apartment-Finder/issues/15

## 

Guilherme Santos Galvão Baptista
UW-Madison Exchange Student - CS Major
UFCG Undergraduate Student - CS Major
LSD (Distributed Systems Laboratory) Former Scholar
OurGrid Former Developer

**Comment by aeggum** [comment]
Hmm..weird.  I just sent you an invite to chat on gmail.  Hopefully it can get figured out.  

Can you access the admin page locally?  Or on heroku? Or neither?

**Comment by xibaca** [comment]
Neither.. I could access it a few days ago, though.

I did not receive your gtalk invitation!

**Comment by xibaca** [comment]
Hey, I tryied logging in with a@a.com and password "password" again, and this time I actually was redirected to the Admin page!

It did not work the last time I tried, that is why I said that!

**Comment by aeggum** [comment]
I tried to make you and Cory admins with your regular accounts, too.  Let me know if you aren't, I'd have to look into it.

**Comment by xibaca** [comment]
My account seemed to be just a regular account.. but I can't really say now because I forgot which password I used =P
I created that "John Locke" account, you can try giving admin power to that one and I can check and see if it worked.

**Comment by aeggum** [comment]
Ok, give it a try, you should be an admin now. 

And if you want to re-make the other account, I deleted it.  Once you re-make it I'll give it admin access too.

**Comment by xibaca** [comment]
It worked! I updated my information from John Locke to myself..
