### ISSUE TITLE
"Forgot password?" link.  

### ISSUE THREAD

**Issue by aeggum** [mswysocki/Madison-Student-Apartment-Finder#16]
Needs to be some way to deal with a user losing their password.  
We do not have a copy of the password anywhere,, so the main solution will have to be sending them a new password in an email, or something like that. 

This is **absolutely required** for the application by the final stages.

**Comment by xibaca** [comment]
Yeah, for sure.
But I don't get it when you say we don't have a copy. Don't we store the encrypted password?
Although, it is not needed, if we make it send an email to the user with a link to generate a new password, yeah.

**Comment by aeggum** [comment]
We store an encrypted version of the password but I do not know of any way to convert it back to plain text if someone forgot theirs.  

So the email to reset or generate a new one would have to be the way to go.  

Hopefully once I get 537 and most of 540 done I can start on it.

**Comment by xibaca** [comment]
I see...
I will keep up working after I have 540 done as well.. I barely started it! =X

**Comment by aeggum** [comment]
I'm going to start on this tonight, hopefully.

If I'm having too much trouble with the implementation I might start looking into some options for different user authentication as a whole, but I doubt it will come to that.

**Comment by xibaca** [comment]
Yeah, I may start working on styling the review and rate features. I`m not sure up to which point have them been implemented yet, I`ll take a look at the code tonight.

**Comment by aeggum** [comment]
So Justin has added this feature, but it's impossible to completely test locally, and it won't be able to work on heroku until the app's owner has verified his account, so we're waiting on Matt. 

They need verification in case we decide to upgrade the mailing account to a paying one. All is free, though, and it should be able to send out 200 messages a day if we want to. 

Right now on Heroku if you try this feature it will cause an error.. but hopefully that won't be the case soon!

**Comment by aeggum** [comment]
Password reset works on Heroku.
