### ISSUE TITLE
Search Bar sliding problem

### ISSUE THREAD

**Issue by xibaca** [mswysocki/Madison-Student-Apartment-Finder#17]
I notice that if you click too much in the box (more precisely, while the sliding effect is still taking place) then it kind of spoils the box and the content is left somewhere in the middle of the transition as well as the sliding effect doesn't work properly afterwards.

I think that in order to fix that we may need to somehow make the user unable to click the option while the sliding effect is still happening.

**Comment by aeggum** [comment]
I've seen it and I agree with you.

Also, something else I'm wondering about is, when you submit a search with search criteria, the results show up as the page loads (as they should) and then the search fields slowly transition to showing up again..

Is there any way to get the search criteria to be open automatically, without the transition?

**Comment by xibaca** [comment]
I know what you mean.. I think we can correct that, but it may be harder than expected, because we are using a built-in library. We can see if the library provides us a way to doing that, all I know so far is that it has the slideUp and slideDown functions.

**Comment by cromdenne** [comment]
I fixed this with a simple delay function in the javascript, so I'm going to close the issue.

**Comment by xibaca** [comment]
I should say that was a smart way of solving it!
