### ISSUE TITLE
RubyGem Issue

### ISSUE THREAD

**Issue by xibaca** [mswysocki/Madison-Student-Apartment-Finder#18]
After I pulled the latest changes, I'm receiving this error message when I try to set up a server ("rails server" command)

$ rails server
C:/Program Files/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems.rb:926:in `report_activate_error': Could not find RubyGem rails (>= 0) (Gem::LoadError)
        from C:/Program Files/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems.rb:244:in`activate_dep'
        from C:/Program Files/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems.rb:236:in `activate'
        from C:/Program Files/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems.rb:1307:in`gem'
        from C:/RailsInstaller/Ruby1.9.2/bin/rails:18:in `<main>'

$

Any of you guys are having the same issue?

**Comment by cromdenne** [comment]
I'm not seeing this issue.  I'm able to run rails server and my localhost:3000 is responding correctly.

There have been a couple of times after I've pulled that I've had to run "bundle install" to get things to work, but I don't know what else to tell you...

**Comment by aeggum** [comment]
I'm not..
Almost looks like it's saying it can't find rails on your system, or 
something.

**Comment by xibaca** [comment]
Thanks guys. I have no idea what happened, I'll try re-installing Rails here again.

**Comment by xibaca** [comment]
Hahaha I have no idea how I could fix this issue.

All I did was remove a folder containing a Ruby installation after trying to reinstall Rails entirely several times (with no luck) and then it is working again...
