### ISSUE TITLE
Generate admin users from the admin page.

### ISSUE THREAD

**Issue by aeggum** [mswysocki/Madison-Student-Apartment-Finder#19]
I came across an issue while Justin was generating some code for issue #16.  

The way admin users are generated right now can only happen through the rails console.  This won't work with the new features being implemented.  So..

Need to make some changes so that all users are non-admins by default (as it is currently), but allow admin users to create other users that are administrators by default.  

This seems like the best option, for a couple of reasons. 
1. Even more unlikely that a non-admin can become an admin.
2. It is user (in this case) admin friendly
3. Still avoids an 'admin' checkbox when making a new user, which isn't necessary.

**Comment by xibaca** [comment]
I agree.. that makes sense.

2012/4/20 Adam Eggum <
reply@reply.github.com

> I came across an issue while Justin was generating some code for issue #16.
> 
> The way admin users are generated right now can only happen through the
> rails console.  This won't work with the new features being implemented.
>  So..
> 
> Need to make some changes so that all users are non-admins by default (as
> it is currently), but allow admin users to create other users that are
> administrators by default.
> 
> This seems like the best option, for a couple of reasons.
> 1. Even more unlikely that a non-admin can become an admin.
> 2. It is user (in this case) admin friendly
> 3. Still avoids an 'admin' checkbox when making a new user, which isn't
> necessary.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mswysocki/Madison-Student-Apartment-Finder/issues/19

## 

Guilherme Santos Galvão Baptista
UW-Madison Exchange Student - CS Major
UFCG Undergraduate Student - CS Major
LSD (Distributed Systems Laboratory) Former Scholar
OurGrid Former Developer

**Comment by aeggum** [comment]
Completed this.
