### ISSUE TITLE
Heroku owner (Matt) needs to verify account

### ISSUE THREAD

**Issue by aeggum** [mswysocki/Madison-Student-Apartment-Finder#21]
To use the add-on we are going to be trying for sending emails (forgot password), the owner of the Heroku account needs to verify their account.  

**The add-on is free**, but they need payment information in the case we want to upgrade. 
This is the add-on we are using: https://devcenter.heroku.com/articles/sendgrid
Here's more information about billing: https://devcenter.heroku.com/categories/billing

And this is what you need to do: https://devcenter.heroku.com/articles/account-verification

Once you verify we can make sure the new forgot password feature is working, or start looking for alternatives.

**Comment by mswysocki** [comment]
Sorry for the delay, I verified the heroku account and added the sendgrid addon to the project. Was this what you were asking about last night?

**Comment by aeggum** [comment]
Sounds good, looks like the password reset feature is now working!
Thanks.

And yep, this was it.
