### ISSUE TITLE
Site is Not Usable in Internet Explorer < 9

### ISSUE THREAD

**Issue by bfrisch** [mswysocki/Madison-Student-Apartment-Finder#23]
In Internet Explorer < 9 the site is not usable as in IE < 9 tags it doesn't recognize, ie the HTML5 Section tags, are not rendered with the proper default styles and don't participate in style inheritance like they should.  (They may not even print.)

I fixed this by adding a reference to the html5shiv in application.html.erb from http://code.google.com/p/html5shiv/ which addresses that problem through JavaScript in the upcoming merge request.  I just followed a Ruby tutorial to try to figure out where to place it, so feel free to not accept if you think the reference to html5shiv should go somewhere else or want to take another approach to IE < 9.  Alternatively, if you just prefer that IE < 9 is not going to be supported there should probably be a message that appears directing the user to download another browser instead of just a broken site.  (Note: the transitions, shadows, and rounded corners support doesn't exist in IE < 9.)

**Comment by aeggum** [comment]
Thanks. 

We haven't been developing with IE < 9 in mind to this point, so I'll take the merge request.

**Comment by xibaca** [comment]
As Adam said, we didn't really consider IE so far, so thanks so much for that!

Any help is good. I'll try testing the website on IE < 9 later, I have IE9 here in my machine, so I couldn't see the result of your work yet.

Thanks again!
