### ISSUE TITLE
Duplicate body tags

### ISSUE THREAD

**Issue by kongyang80** [mswysocki/Madison-Student-Apartment-Finder#25]
Severity: Low

I noticed that in the Add Listing page, the HTML source code contained two <body> tags as well has two <html> tags. Well it seems like the page is able to load fine so this is probably not a big issue. I'm just worried it might affect the layout.

**Comment by xibaca** [comment]
Thanks for reporting that. We've redesigned the CSS several times, but these small things may still be around somewhere. We will be working extensively in the html and css files very soon, possibly using twitter bootstrap, so we will be more careful.

**Comment by aeggum** [comment]
Fixed. 
It looks like we just forgot remove the html and body tags from the file.  

They aren't needed in any of the files, as they are in the main file (application.html.erb)
