### ISSUE TITLE
Login status message displaying below the layout

### ISSUE THREAD

**Issue by kongyang80** [mswysocki/Madison-Student-Apartment-Finder#27]
Severity: Low

It looks like the login status message such as "Invalid email/password combination." appears below the red layout. It's in white text so it's barely visible.

**Comment by xibaca** [comment]
The feature is already functional but we need to enhance its appearance (as well as the website as a whole). It is still a work in progress.
Thanks!

**Comment by aeggum** [comment]
We no longer show this text, for now.  With a redesign coming in the future I'll close this for now.
