### ISSUE TITLE
Main heading links directly to the live website

### ISSUE THREAD

**Issue by aeggum** [mswysocki/Madison-Student-Apartment-Finder#3]
Can this be change so that it is local (ie. links to the main page but not necessarily msaf.heroku.com)?

Even on my local copy when I click the heading it open the actual webpage rather than taking me to the home page.

**Comment by cromdenne** [comment]
Yea, that's a good idea. I just changed it, it's live.

**Comment by aeggum** [comment]
Yeah, looks like it works now.  Now it is a global button as well.
