### ISSUE TITLE
Email privacy

### ISSUE THREAD

**Issue by kongyang80** [mswysocki/Madison-Student-Apartment-Finder#33]
Priority: Medium

I noticed that when I logged in, my URL was http://msaf.heroku.com/users/14 on http://msaf.heroku.com

I guess you can just enter any number like http://msaf.heroku.com/users/13 and see a user's profile which contains their email. I saw that http://msaf.heroku.com/users/3 had the name Admin email.

**Comment by xibaca** [comment]
Oh yeah... This is a concern.. Thanks for pointing that out!

**Comment by aeggum** [comment]
Just committed a fix for this.  Will push it later. Only you and admins can see your profile page. 

Thanks.
