### ISSUE TITLE
Image Hosting - Can't use Heroku directly

### ISSUE THREAD

**Issue by aeggum** [mswysocki/Madison-Student-Apartment-Finder#39]
The best (and well supported) option is to use Amazon's S3 for image hosting and CarrierWave, the image uploader we're using.   (As you can see right now, you can try to upload an image on the site and it will give you an error : http://msaf.heroku.com/lists/3/edit ).

Here is some information: https://github.com/jnicklas/carrierwave#using-amazon-s3
Here is info about S3: http://aws.amazon.com/s3/#getting-started , http://aws.amazon.com/free/
More: https://devcenter.heroku.com/articles/s3

For the first year it'd be free for us, and even after that if we did stick with this, it would be very cheap for our purposes.   It's reliable, supported (simply - it looks) with CarrierWave, and free/cheap, so tomorrow I plan on setting up an account and integrating with our project again.  

Does that sound OK, or was there a different solution someone had for how to deal with images?
Hopefully I can get this settled by tomorrow, and then it's mostly left to UI redesign, general improvements/UX stuff, and landlord integration before the demo.

**Comment by cromdenne** [comment]
This sounds good to me.

I changed the banner to a bootstrap implementation and pushed to the UI_redesign branch, but I probably won't have time to do any of the other UI stuff until Thursday or Friday.  After that I shouldn't have any other work to worry about, so then I can bunker down and finish up all of the bootstrap implementation.  Doing the banner wasn't too difficult, and I don't anticipate that any of the other pages will be either.

I hope to finish the bootstrap redesign and merge by the end of the weekend, and then clean up any loose ends and work with the google maps stuff early next week.

**Comment by aeggum** [comment]
Image uploading works on heroku now, using Amazon's S3 cloud.  
It's all free for now so that's pretty awesome.  

Currently no max image size but I'll try to add that soon, as well as the other features I can.

**Comment by aeggum** [comment]
Just running some numbers using the S3 cost stuff here: http://aws.amazon.com/s3/#pricing

If the site just made it HUGE (unrealistically huge), we might have to pay $25 a month.  
That's if users were uploading 100 GBs a month and we were getting 10million hits monthly.
