### ISSUE TITLE
Title is same on each page

### ISSUE THREAD

**Issue by aeggum** [mswysocki/Madison-Student-Apartment-Finder#4]
Not sure if that is what we want,   It seems that even setting the title on a page doesn't do anything.

Feel free to close if this is what we want but I'm not sure.

**Comment by xibaca** [comment]
I'm not sure if that is what we want. I think it should be changing, though! We are setting all kinds of different names for the <title> tags on each file.

**Comment by aeggum** [comment]
So I fixed this issue.  Titles are now dealt with in the controllers, so there should not be any <title></title> calls in any of the html files except for application.html.erb in one of the main folders.

The titles can easily be changed to what we want them to be inside the controllers.
