### ISSUE TITLE
in landlord listing make items in list clickable

### ISSUE THREAD

**Issue by theodora** [mswysocki/Madison-Student-Apartment-Finder#42]
in pages such as http://msaf.heroku.com/landlords/1 the list of houses could be clickable, taking you to the page for that residence.

**Comment by aeggum** [comment]
Thanks.  

Yeah, this was a problem I noticed, it's been fixed but not pushed to Heroku as of yet. 
I'll close this once it's pushed.

**Comment by aeggum** [comment]
It's live on Heroku. Thanks.
