### ISSUE TITLE
Bootstrap issues

### ISSUE THREAD

**Issue by cromdenne** [mswysocki/Madison-Student-Apartment-Finder#45]
I'm trying to implement bootstrap, and I've the got the banner pretty much finished, but there are some issues with it that will be bigger issues when doing other pages.  Mainly, I'm having a lot of trouble with the javascript that's used by the bootstrap CSS.  I'm going to just move forward with the formatting of the pages for now so that we've got that done, and I'll have to look at the javascript issues later.  I'll try to finish the search panel and main page asap, and I've got a mockup that I can copy paste for the add listing page.  If anyone wants to look over the javascript stuff after I push to the UI-redesign branch then you can check if I'm missing something lame.

The dropdown javascript works for the user button when a user is signed in, but the "collapse" effect for the search panel doesn't seem to work (and the same effect for the navbar when you make the page narrower - there's a button that appears that's supposed to make the navbar links a dropdown list).  I'm a bit confused that one effect works but the others don't, as I'm pretty sure that I've linked everything pretty consistently and correctly.

**Comment by aeggum** [comment]
I figured there would be some issues, that kinda stinks though.  Maybe we should consider upgrading to Rails 3.2 if we want to stick with everything.  Obviously that would have to be after the demo though.  

Tomorrow I'll try to pull your branch and take my best shot at some javascript.

**Comment by aeggum** [comment]
I'm struggling to even take a look at the code in your branch.  Seems a little bit weird with Aptana, but hopefully I can figure it out.

**Comment by cromdenne** [comment]
I'm about to push more code, I've been plugging away on a lot of the pages.  The main things that will be left will be the view listing page, the admin page, and the results page.  After I push we can g-chat if you have any questions.

**Comment by aeggum** [comment]
Are you using Aptana?  I think that's my problem, as I can't view any other branches' code differences.  If so I'll be on Gchat and feel free to send me an invitation or however that works

**Comment by cromdenne** [comment]
Ok, yea, I haven't been using Aptana, so that might be the issue.
