### ISSUE TITLE
Suggestion: Make the last space in the navbar a link to home page

### ISSUE THREAD

**Issue by caelestisarah** [mswysocki/Madison-Student-Apartment-Finder#47]
There's a space there anyway, why not have it link back to the search page? I realize that the title links back to the home page, but it would make the navbar look more complete.

**Comment by cromdenne** [comment]
We were hoping to implement bootstrap without any major issues, but that has not been the case.  This issue would have been solved with the bootstrap layout, but since we won't have that ready for the demo, I've implemented the solution suggested above for our interface.
