### ISSUE TITLE
Database needs to change

### ISSUE THREAD

**Issue by aeggum** [mswysocki/Madison-Student-Apartment-Finder#5]
Just writing this as a reminder.  I need to make a few changes to the database, including:

Change :Bedrooms to :integer  ... for some reason I made them strings
Change :Pets to :boolean?  Someone can comment on this.. I think that would be easier than 'cats' or 'dogs' and parsing strings.

Also, once that is done, need to add indexes to the main search fields (address, rent, rooms) for faster searching

**Comment by xibaca** [comment]
I think that Pets is best as a boolean too! Even for displaying purposes, as the other field that is next to (the Smoking) is a boolean.

**Comment by aeggum** [comment]
Sounds good.  That's what I was thinking too.  The next time I do a migration I'll make sure to make that change.

**Comment by xibaca** [comment]
Ok. I'll work on the CSS of the main page, try to change the appearance of
the search button and then work in the css of the search display results.

But I think the core funcionality of the website is pretty decent! Well
done everyone!

Is there any urgent thing to be done yet?

2012/3/23 Adam Eggum <
reply@reply.github.com

> Sounds good.  That's what I was thinking too.  The next time I do a
> migration I'll make sure to make that change.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/mswysocki/Madison-Student-Apartment-Finder/issues/5#issuecomment-4652910

## 

Guilherme Santos G. Baptista
Graduando em Cincia da Computao pela UFCG
LSD - Laboratrio de Sistemas Distribudos

**Comment by aeggum** [comment]
Hold up on the css.  I've been making some small changes, let me commit.

I don't think it would be a bad idea to remove scaffold.css and then bring out some of the css stuff into their own files afterwards, thats what I was working towards.

**Comment by xibaca** [comment]
Ok, sounds fine!

2012/3/23 Adam Eggum <
reply@reply.github.com

> Hold up on the css.  I've been making some small changes, let me commit.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/mswysocki/Madison-Student-Apartment-Finder/issues/5#issuecomment-4652964

## 

Guilherme Santos G. Baptista
Graduando em Cincia da Computao pela UFCG
LSD - Laboratrio de Sistemas Distribudos

**Comment by aeggum** [comment]
Done.

And allow me to say..deploying db changes to heroku is pretty scary when we have no backup site guaranteed to work. Hopefully I get better at it as time progresses.

**Comment by xibaca** [comment]
Hahaha I can wonder.. I never feel confident about dbs.
I hope we can get things really robust as time passes.

2012/3/23 Adam Eggum <
reply@reply.github.com

> Done.
> 
> And allow me to say..deploying db changes to heroku is pretty scary when
> we have no backup site guaranteed to work. Hopefully I get better at it as
> time progresses.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/mswysocki/Madison-Student-Apartment-Finder/issues/5#issuecomment-4653763

## 

Guilherme Santos G. Baptista
Graduando em Cincia da Computao pela UFCG
LSD - Laboratrio de Sistemas Distribudos
