### ISSUE TITLE
[Small Issue] Type of Residence radio buttons

### ISSUE THREAD

**Issue by xibaca** [mswysocki/Madison-Student-Apartment-Finder#7]
At the Search Sidebar, the Type of Residence Criteria contains a weird set of radio buttons. One can click on an option and then click in the other, and then none can be deselected.

I tried fixing it, but I don't know how to do that. =P

**Comment by xibaca** [comment]
Now, the Clear Criterias button is implemented, so if what is happening above is what we want, fell free to close this issue.

**Comment by aeggum** [comment]
I'll take a look at this when I get the chance.  Probably something small.
