### ISSUE TITLE
CSS button transition effects not working for Show, Edit and Remove

### ISSUE THREAD

**Issue by xibaca** [mswysocki/Madison-Student-Apartment-Finder#9]
I tried to get it working, but without success. I can't figure out why. It should, as I just copied the same code from the Search button, which is working just fine.

Any thoughts?

**Comment by aeggum** [comment]
they look like they are working as the submit button does to me?
I just see them lighting up and then fading away.  Could it be a browser or computer specific problem or is that the wrong behavior?

**Comment by xibaca** [comment]
Here, it does light up and fades away, but, differently that the submit button, all instantly, there is no transition effect from one style to the other.

Does this transition happen for you? I just tried here at chrome, maybe it is something wrong with my browser. But I still can see the submit effects, though.

**Comment by aeggum** [comment]
I don't know, it looks like it's doing the transition right (and similar to the submit button) for me but maybe I don't know what it should actually be doing..  but if it's not working for you that definitely sounds like a bug...so idk
